name = "OscoNet"
uuid = "cb41ad35-20b8-4d40-9b6b-f147609bef6d"
authors = ["Joshua Burton"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
